language: cpp

compile:
  - gcc
  - clang

before_install:
  - sudo apt-get update
  - sudo apt-get install libboost-dev

script:
  - git clone https://github.com/eigenteam/eigen-git-mirror eigen
  - EIGENDIR=$(pwd)/eigen
  - mkdir build
  - cd build
  - cmake -DEIGEN3_INCLUDE_PATH=${EIGENDIR} ../invlib


